### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by ZyadMohamed1** [SenHe/Flow-Style-VTON#12]
When trying to train on the Viton Dataset it gives this error

`RuntimeError: Given input size: (512x2x1). Calculated output size: (512x1x0). Output size is too small`

What is the issue

**Comment by Jerome-Young** [comment]
I have the same problem in stage 1

**Comment by SenHe** [comment]
This is a problem caused by different PyTorch version.
Please double check your PyTorch version or you can modify the [forward function ](https://github.com/SenHe/Flow-Style-VTON/blob/1e5df26abab4ef1fce9ec75cc27b250c011fe639/train/models/networks.py#L145) and [loss computation](https://github.com/SenHe/Flow-Style-VTON/blob/1e5df26abab4ef1fce9ec75cc27b250c011fe639/train/models/networks.py#L163) accordingly.
